ALTER TABLE usuario ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(255);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS account_verified BOOLEAN DEFAULT FALSE;
